//
// Created by Lukas Tenbrink on 20.02.20.
//

#ifndef LED_FAN_SETUP_H
#define LED_FAN_SETUP_H

#define MAGNET_PINS 33

#define HOST_NETWORK_SSID "LLED Fan"
#define HOST_NETWORK_PASSWORD "We love LED"

#define MAX_FRAMES_PER_SECOND 2000

#define LED_TYPE WS2813
#define COLOR_ORDER GRB
#define LED_PIN 25
#define LED_COUNT 18

#define VIRTUAL_SCREEN_SIZE 64
#define CONCENTRIC_RESOLUTION_MIN 4
#define CONCENTRIC_RESOLUTION_ADD 4

// See ROTATION_SENSOR_TYPE_XXX
#define ROTATION_SENSOR_TYPE ROTATION_SENSOR_TYPE_HALL_SYNC
#define ROTATION_SENSOR_MS 1

#endif //LED_FAN_SETUP_H
